console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  # newline = true

  [[blocks.segments]]
    type = "python"
    style = "plain"
    # foreground = "= 'p:purple'"
    # template = '{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}({{ .Venv }}) {{ end }}{{ .Full }} {{ end }}'
    template = '{{ if .Error }}{{ .Error }}{{ else }}({{ if .Venv }}{{ .Venv }}{{ else }}{{ .Full }}{{ end }}) {{ end }}'
    foreground = 'p:pink'

    [blocks.segments.properties]
      display_mode = "environment"
      fetch_virtual_env = true
      folder_name_fallback = false
      home_enabled = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    background = 'transparent'
    # foreground = 'p:pink'
    foreground = 'p:grey'
    # template = " [<cyan>{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}</>{{ end }}<green>{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if .Working.Changed }} <red>{{ .Working.String }}</>{{ end }}</>]"
    template = """ \
[<cyan>{{if not .Detached}}{{ .HEAD }}{{else}}@{{ printf "%.7s" .Commit.Sha }}{{end}}\
{{if .BranchStatus }} {{ .BranchStatus }}</>{{ end }}\
<green>{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if .Working.Changed }} <red>{{ .Working.String }}</>{{ end }}</>]\
"""
  # template = " [<cyan>{{ .HEAD }}{{if .BranchStatus }} <green>{{ .BranchStatus }}</>{{ end }}{{ if .Working.Changed }} <red>* {{ .Working.String }}</>{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}</>]"
  # template = " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uF044 {{ .Working.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uF046 {{ .Staging.String }}{{ end }}"
  # template = ' <#5FAAE8>git(<yellow>{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}</><cyan>{{ if gt .Behind 0 }} ⇣{{ end }}{{ if gt .Ahead 0 }}^{{ end }}</>)</>'
  # template = ' git(<yellow>{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}</><cyan>{{ if gt .Behind 0 }} ⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>)'
  # template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true
      branch_ahead_icon = '+'
      branch_behind_icon = "\u2013"

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    background = 'transparent'
    foreground = 'yellow'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 3000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  # newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = [
      '{{if gt .Code 0}}red{{end}}',
      '{{if eq .Code 0}}magenta{{end}}'
    ]

[transient_prompt]
  foreground_templates = [
    '{{if gt .Code 0}}red{{end}}',
    '{{if eq .Code 0}}magenta{{end}}'
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  background = 'transparent'
  foreground = 'magenta'
  template = '❯❯ '

[palette]
  grey = '#6c6c6c'
  pink = '#D0666F'
  purple = '#C678DD'