#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = "python"
    style = "plain"
    template = '{{ if .Error }}{{ .Error }}{{ else }}({{ if .Venv }}{{ .Venv }}{{ else }}{{ .Full }}{{ end }}) {{ end }}'
    foreground = 'p:pink'

    [blocks.segments.properties]
      display_mode = "environment"
      fetch_virtual_env = true
      folder_name_fallback = false
      home_enabled = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:grey'
    template = """ \
[<cyan>{{if not .Detached}}{{ .HEAD }}{{else}}@{{ printf "%.7s" .Commit.Sha }}{{end}}\
{{if .BranchStatus }} {{ .BranchStatus }}</>{{ end }}\
<green>{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if .Working.Changed }} <red>{{ .Working.String }}</>{{ end }}</>]\
"""

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true
      branch_ahead_icon = '+'
      branch_behind_icon = "\u2013"

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    background = 'transparent'
    foreground = 'yellow'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 3000

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = [
      '{{if gt .Code 0}}red{{end}}',
      '{{if eq .Code 0}}magenta{{end}}'
    ]

[transient_prompt]
  foreground_templates = [
    '{{if gt .Code 0}}red{{end}}',
    '{{if eq .Code 0}}magenta{{end}}'
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  background = 'transparent'
  foreground = 'magenta'
  template = '❯❯ '

[palette]
  grey = '#6c6c6c'
  pink = '#D0666F'
  purple = '#C678DD'